### PR TITLE
Fix Sparkling Aria's interaction with Shield Dust

### LINKED ISSUE #10293: Sparkling Aria cures burns from Pokemon with Shield Dust where it shouldn't
Sparkling Aria shouldn't cure burns from Pokemon with Shield Dust (and I'm assuming Covert Cloak too) in Single Battles.
Sparkling Aria correctly cures burns from Pokemon with Shield Dust in Double Battles where Sparkling Aria hits multiple Pokemon.
Sparkling Aria incorrectly cures burns from Pokemon with Shield Dust in Double Battles where Sparkling Aria hits only a single Pokemon.
Singles, shouldn't cure.
20240512_18h01m04s_grim

Doubles, should cure.
20240512_17h52m13s_grim

Doubles, shouldn't cure.
20240512_17h57m44s_grim

### PR DESCRIPTION
**Pull request by andrebastosdias**
Closes #10293 
I don't know if there's already a way to determine how many targets were hit. `spreadHit` doesn't take into account protections, misses, etc.

### CODE REVIEW

**Comment by andrebastosdias** [comment]
I have another version of the code that doesn't change Sparkling Aria and instead makes use of `dustproof`, modifying Shield Dust and Covert Cloak:
```
onModifySecondaries(secondaries, target, source, move) {
	this.debug('Shield Dust prevent secondary');
	const targets = this.getAllActive().filter(p => p.getMoveHitData(move).successful).length;
	return secondaries.filter(effect => !!(effect.self || (effect.dustproof && targets > 1)));
},
```
Let me know which one you prefer!

**Comment by andrebastosdias** [comment]
I have another version of the code that doesn't change Sparkling Aria and instead makes use of `dustproof`, modifying Shield Dust and Covert Cloak:
```
onModifySecondaries(secondaries, target, source, move) {
	this.debug('Shield Dust prevent secondary');
	const targets = this.getAllActive().filter(p => p.getMoveHitData(move).successful).length;
	return secondaries.filter(effect => !!(effect.self || (effect.dustproof && targets > 1)));
},
```
Let me know which one you prefer!

File: data/moves.ts [hunk 1]
```diff
@@ -18049,13 +18049,19 @@ export const Moves: import('../sim/dex-moves').MoveDataTable = {
...
-			for (const pokemon of this.getAllActive()) {
-				if (pokemon !== source && pokemon.removeVolatile('sparklingaria') && pokemon.status === 'brn' && !source.fainted) {
+			if (source.fainted || !move.hitTargets || move.hasSheerForce) {
+				// make sure the volatiles are cleared
+				for (const pokemon of this.getAllActive()) delete pokemon.volatiles['sparklingaria'];
+				return;
+			}
+			const numberTargets = move.hitTargets.length;
+			for (const pokemon of move.hitTargets) {
+				if (pokemon !== source && pokemon.isActive && (pokemon.removeVolatile('sparklingaria') || numberTargets > 1) &&
```
Comment (Zarel) [inline data/moves.ts:18063]:
```suggestion
				if (pokemon !== source && pokemon.isActive && (pokemon.removeVolatile('sparklingaria') || numberTargets > 1) &&
```
This seems to imply that Sparkling Aria doesn't bypass Shield Dust in singles?

Comment (Zarel) [reply data/moves.ts:18063]: Okay yeah I should have looked at the test, all right, this looks good.

**Comment by Zarel** [comment]
Thanks!
