### PR TITLE
Fix Gen 1 multi-turn move interactions with Haze, Metronome and Mirror Move

### LINKED ISSUE #11858: Gen 1 Game-Breaking Wrap Bug
Players on the gen 1 OU ladder noticed a bug that rendered their Pokémon completely incapable of taking any actions after getting Wrapped, including burning sleep turns. This can be seen in the replays below.

REPLAY 1: From the ladder, a Snorlax sleeping from Rest is seen not burning sleep turns. The UI shows the Snorlax's only option as the Fight button.
https://replay.pokemonshowdown.com/gen1ou-2567438803-q14kxji78qkxx6dxov9pxt9hcskxd8tpw?p2

REPLAY 2: A recreation of the above replay, but on turn 63, after many turns of being unresponsive, the Snorlax wakes up. Also to be noted, on turns 30-32, we see Tauros get hit by Wrap, its "Tauros is unable to move!"message not showing up, but it's still able to move on turn 32.
https://replay.pokemonshowdown.com/gen1ou-2567557100

We've done a bit of testing and have found it to be very specific, the bug making Snorlax freeze has only been replicated so far in this exact situation. However, considering it's come up in a ladder game within days of the new Fight button being introduced, it's fair to say the current implementation would eventually cause problems in real tournament sets.

### PR DESCRIPTION
**Pull request by andrebastosdias**
Fixes #11858 (the mechanic is correct, but it adds a hint message).
https://www.smogon.com/forums/threads/fly-called-by-metronome-shouldnt-cause-a-desync-in-gen-1.3779996/

The glitch (the original glitch of this PR) occurs when Haze clears the sleep or freeze status of a Pokémon during the execution of a multi-turn move. If this happens, the Pokémon becomes soft-locked, unable to finish the move or switch out. This also affects Hyper Beam's recharge turn. In the case of Bide, the move still cannot be completed, but the Pokémon is able to switch out.

Edit: This PR touches a lot of logic related to locked moves and there was one move in particular that was poorly implemented: Bide. Bide doesn't disable the other moves, but it "semi-locks" you into using it. By semi-locking, I mean that it allows you to switch out, but if you click the Fight button, your action is submitted instantly.

I introduced a new `SemiLockedMove` event that works similarly to the `LockedMove` event. It is applied to the following effects:

* Gen 1 partially trapping moves during the first two turns (after that, you don’t know if you are still trapping).
* Gen 1 partially trapped (semi-locked to "Fight" during the first two turns. After that, you don't know if you are still trapped).
* Gens 1 and 2 Bide (in Gen 3, you can't switch out after selecting Bide. Gen 2 was wrongly implemented like Gen 3).
* Gens 2-4 Encore (in these early gens, the encored move should be submitted as soon as you click the Fight button, and you can't choose a target in doubles—after this PR gets merged, it will be implemented in #11846).

Edit:
* If Metronome or Mirror Move calls a partial trapping move, the effect should persist for the duration.
* If the target switches and the move was called by Metronome, the Pokémon will use Metronome (there is hardcoded logic that changes the last move used to "Metronome" while trapping).
* If the target switches and the move was called by Mirror Move, desync clause activates and the trapping effect ends (Mirror Move was not included causing the "Partial trapping move Mirror Move link battle glitch").

### CODE REVIEW

File: data/mods/gen1/scripts.ts [hunk 1]
```diff
@@ -146,31 +146,43 @@ export const Scripts: ModdedBattleScriptsData = {
 				}
 			}
 
-			// If a faster partial trapping move misses against a user of Hyper Beam during a recharge turn,
-			// the user of Hyper Beam will automatically use Hyper Beam during that turn.
-			if (move.id === 'recharge' && !pokemon.volatiles['mustrecharge'] && !pokemon.volatiles['partiallytrapped']) {
-				move = this.battle.dex.getActiveMove('hyperbeam');
-				this.battle.hint(`In Gen 1, partial trapping moves like Wrap remove Hyper Beam recharges. ` +
-					`If the target would have recharged, it will automatically use Hyper Beam instead.`, true);
```
Comment (andrebastosdias) [inline data/mods/gen1/scripts.ts:154]: This is now covered by setting `choice.moveid` to `lastMoveSelected` (Hyper Beam).
```
choice.moveid = this.lastSelectedMove || '00' as ID;
```

File: sim/pokemon.ts [hunk 2]
```diff
@@ -941,21 +941,36 @@ export class Pokemon {
 	 * Sky Drop, which remove all choice (no dynamax, switching, etc).
 	 * Don't use it for "soft locks" like Choice Band.
 	 */
-	getLockedMove(): ID | null {
+	getLockedMove(includeSemiLocked?: boolean): ID | null {
```
Comment (Slayer95) [inline sim/pokemon.ts]: If there's only one callsite to ``getLockedMove(true)``, consumption as ``getLockedMove() || getSemiLockedMove()`` is clearer.

**Comment by andrebastosdias** [comment]
Okay, I'm finished.

**Comment by andrebastosdias** [comment]
More bugs were reported regarding partial trapping interactions and Metronome/Mirror Move. Fixed!

**Comment by Zarel** [comment]
Thanks!
